// <auto-generated />
namespace Journal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class init21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init21));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271751490_init21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
