// <auto-generated />
namespace Journal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migrationfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationfix));
        
        string IMigrationMetadata.Id
        {
            get { return "202001262035287_migration-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
